#!/usr/bin/env bash

CONFIG_DIR_YADM=$HOME/.config/yadm/

if [[ `lsb_release -si` = 'VoidLinux' ]]
then 
  echo "yadm - VoidLinux bootstrap"
  . $CONFIG_DIR_YADM/bootstrap-files/void-install
  . $CONFIG_DIR_YADM/bootstrap-files/zsh
  
fi

#. $CONFIG_DIR_YADM/bootstrap-files/tpm
#. $CONFIG_DIR_YADM/bootstrap-files/nvim

