#!/usr/bin/env bash

echo Begin Neovim setup

if ! [ -x $(command -v nvim > /dev/null 2>&1) ]
then
  echo TODO: convert it to submodule
  #git clone https://github.com/maxdevjs/dotfiles-nvim $HOME/.config/nvim
fi

if [[ ! -f $HOME/.local/share/nvim/site/autoload/plug.vim ]]
then
  echo installing plug.vim
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [[ ! -d $HOME/.local/share/nvim/plugged ]]
then
  echo "Bootstraping Neovim"
  #nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

echo End Neovim setup
